# Generated by Django 3.0.8 on 2020-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
